cask "font-caskaydia-mono-nerd-font"
cask "font-droid-sans-mono-nerd-font"
cask "font-go-mono-nerd-font"
cask "font-blex-mono-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro"
cask "font-ubuntu-nerd-font"
cask "font-fira-code-nerd-font"
