[checks]
    min_battery_percent = 20.0
    max_cpu_load_percent = 50.0
    max_mem_percent = 90.0
    network_not_metered = true  # Abort if network connection is metered
[notify]
    dbus_notify = false
