#!/usr/bin/env bash

# SCRIPT VERSION
GROUP_SETUP_VER=1
GROUP_SETUP_VER_FILE="/etc/ublue/dx-groups"
GROUP_SETUP_VER_RAN=$(cat "$GROUP_SETUP_VER_FILE")

# Run script if updated
if [[ -f $GROUP_SETUP_VER_FILE && "$GROUP_SETUP_VER" = "$GROUP_SETUP_VER_RAN" ]]; then
  echo "Group setup has already run. Exiting..."
  exit 0
fi

# Copy relevant groups from /usr/lib/group to /etc/group so they can have users added
cat /usr/lib/group | grep 'docker:\|incus-admin:\|lxd:\|libvirt:' | tee -a /etc/group >/dev/null

# Setup Groups
wheelarray=($(getent group wheel | cut -d ":" -f 4 | tr  ',' '\n'))
for user in $wheelarray
do
  usermod -aG docker $user
  usermod -aG incus-admin $user
  usermod -aG lxd $user
  usermod -aG libvirt $user
done

# Prevent future executions
echo "Writing state file"
echo "$GROUP_SETUP_VER" > "$GROUP_SETUP_VER_FILE"
