[misc]
no_self_update = true
disable = ["containers", "git", "helm", "self_update", "toolbx"]
ignore_failures = ["brew_cask", "brew_formula", "distrobox", "firmware", "flatpak", "home_manager", "nix", "node", "pip3"]
assume_yes = true
no_retry = false

[linux]
rpm_ostree = true
