#!/usr/bin/bash

# Script Version
VER=5
VER_FILE="${XDG_DATA_HOME:-$HOME/.local/share}/ublue/flatpak_manager_version"
VER_RAN=$(cat $VER_FILE)

mkdir -p "$(dirname "$VER_FILE")" || exit 1

# Upgrade from v1 to v2 changes only the location of the VER_FILE.
# Exit if v1 file is present.
VER_1_FILE="$HOME/.ublue_flatpak_manager_version"
if [[ -f $VER_1_FILE  ]]; then
  echo "Networked tasks v$VER has already ran. Exiting..."
  rm $VER_1_FILE
  echo $VER > $VER_FILE
  exit 0
fi

# Run script if updated
if [[ -f $VER_FILE && $VER = $VER_RAN ]]; then
  echo "Flatpak manager v$VER has already ran. Exiting..."
  exit 0
fi

# Enable Flathub
if grep -qz 'fedora' <<< $(flatpak remotes); then
  flatpak remote-delete --user fedora --force
fi
flatpak remote-add --if-not-exists --user flathub /usr/etc/flatpak/remotes.d/flathub.flatpakrepo
flatpak remote-modify --user --enable --prio=2 flathub

# Lists of flatpaks
FLATPAK_LIST=$(flatpak list --columns=application)
INSTALL_LIST=$(cat /etc/flatpak/user/install)
REMOVE_LIST=$(cat /etc/flatpak/user/remove)

# Install flatpaks in list
if [[ -n $INSTALL_LIST ]]; then
  if ! flatpak install --user --noninteractive flathub ${INSTALL_LIST[@]}; then
    # exit on error
    exit 1
  fi
fi

# Remove flatpaks in list once
if [[ ! -f $VER_FILE && -n $REMOVE_LIST ]]; then
  flatpak remove --user --noninteractive ${REMOVE_LIST[@]}
fi

notify-send "Flatpak installer" "Finished installing user flatpaks" --app-name="Flatpak installer" -u NORMAL

echo $VER > $VER_FILE
