#!/usr/bin/bash

# Enable NTP
timedatectl set-ntp true

# Allow Tailscale Control
tailscale set --operator="$(getent passwd $PKEXEC_UID | cut -d: -f1)"

# Install brew
if [[ ! -x /var/home/linuxbrew/.linuxbrew/bin/brew ]]; then
	NONINTERACTIVE=1 /usr/libexec/brew-install
fi
