FROM ghcr.io/ublue-os/fedora-distrobox:latest
# From https://github.com/ublue-os/fedora-distrobox

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the toolbox or distrobox command" \
      summary="A cloud-native terminal experience powered by Fedora" 

COPY ./toolboxes/packages.fedora /toolbox-packages

RUN dnf -y upgrade && \
    dnf -y install $(<toolbox-packages) && \
    dnf clean all

RUN rm /toolbox-packages
