#!/usr/bin/bash
escape() {
	sed 's/[&/\]/\\&/g' <<< "$1"
}

TIP_FILE=$(find /usr/share/ublue-os/motd/tips/*.md | shuf -n 1)
if [[ -f "$TIP_FILE" ]]; then
	IMAGE_INFO="/usr/share/ublue-os/image-info.json"
	IMAGE_NAME=$(jq -r '."image-name"' < $IMAGE_INFO)
	IMAGE_NAME_ESCAPED=$(escape "$IMAGE_NAME")
	IMAGE_TAG=$(jq -r '."image-tag"' < $IMAGE_INFO)
	IMAGE_TAG_ESCAPED=$(escape "$IMAGE_TAG")
	TIP="󰋼 $(shuf -n 1 "$TIP_FILE")"

	IMAGE_DATE=$(rpm-ostree status --booted | sed -n 's/.*Timestamp: \(.*\)/\1/p')
	IMAGE_DATE_SECONDS=$(date -d "$IMAGE_DATE" +%s)
	CURRENT_SECONDS=$(date +%s)
	DIFFERENCE=$((CURRENT_SECONDS - IMAGE_DATE_SECONDS))
	MONTH=$((30 * 24 * 60 * 60))
	if [ "$DIFFERENCE" -ge "$MONTH" ]; then
		#shellcheck disable=2016
		TIP='# 󰇻 Your current image is over 1 month old, run `ujust update`'
	fi

	TIP_ESCAPED=$(escape "$TIP")

fi

KEY_WARN_FILE="/run/user-motd-sbkey-warn.md"
[ -e $KEY_WARN_FILE ] && KEY_WARN="**WARNING**: $(cat $KEY_WARN_FILE)"
KEY_WARN_ESCAPED=$(escape "$KEY_WARN")

THEME=$(gsettings get org.gnome.desktop.interface accent-color || echo "'slate'")
THEME=${THEME//\'/}
COLOR_SCHEME=$(gsettings get org.gnome.desktop.interface color-scheme || echo "'prefer-dark'")
COLOR_SCHEME=${COLOR_SCHEME//\'/}
case $COLOR_SCHEME in
	"default")
		COLOR_SCHEME="light"
		;;
	*)
		COLOR_SCHEME="dark"
		;;
esac

sed -e "s/%IMAGE_NAME%/$IMAGE_NAME_ESCAPED/g" \
	-e "s/%IMAGE_TAG%/$IMAGE_TAG_ESCAPED/g" \
	-e "s/%TIP%/$TIP_ESCAPED/g" \
	-e "s/%KEY_WARN%/$KEY_WARN_ESCAPED/g" \
	/usr/share/ublue-os/motd/bluefin.md | tr '~' '\n' | /usr/bin/glow -s /usr/share/ublue-os/motd/themes/$COLOR_SCHEME/$THEME.json -w 78 -
