#!/usr/bin/bash
escape() {
	sed 's/[&/\]/\\&/g' <<< "$1"
}

TIP_FILE=$(find /usr/share/ublue-os/motd/tips/*.md | shuf -n 1)
if [[ -f "$TIP_FILE" ]]; then
	IMAGE_INFO="/usr/share/ublue-os/image-info.json"
	IMAGE_NAME=$(jq -r '."image-name"' < $IMAGE_INFO)
	IMAGE_NAME_ESCAPED=$(escape "$IMAGE_NAME")
	IMAGE_TAG=$(jq -r '."image-tag"' < $IMAGE_INFO)
	IMAGE_TAG_ESCAPED=$(escape "$IMAGE_TAG")
	TIP="󰋼 $(shuf -n 1 "$TIP_FILE")"

	IMAGE_DATE=$(rpm-ostree status --booted | sed -n 's/.*Timestamp: \(.*\)/\1/p')
	IMAGE_DATE_SECONDS=$(date -d "$IMAGE_DATE" +%s)
	CURRENT_SECONDS=$(date +%s)
	DIFFERENCE=$((CURRENT_SECONDS - IMAGE_DATE_SECONDS))
	MONTH=$((30 * 24 * 60 * 60))
	if [ "$DIFFERENCE" -ge "$MONTH" ]; then
		#shellcheck disable=2016
		TIP='# 󰇻 Your current image is over 1 month old, run `ujust update`'
	fi

	TIP_ESCAPED=$(escape "$TIP")
fi

# check for secure boot key
KEY_WARN=""
FINGERPRINT="2B:E9:91:E3:B1:B5:40:70:F4:3D:80:BB:13:EB:C6:57:E5:A3:78:0D"
mokutil --list-enrolled | grep -q $FINGERPRINT
ENROLLED=$?
mokutil --sb-state | grep -q enabled
SB_ENABLED=$?

if [[ $ENROLLED -eq 1 ]] && [[ $SB_ENABLED -eq 0 ]]; then
	KEY_WARN="**WARNING**: This machine has secure boot turned on, but you haven't enrolled Universal Blue's keys. Failing to enroll these before rebooting **may cause your system to fail to boot**. Follow this [link](https://docs.projectbluefin.io/introduction#secure-boot) ~for instructions on how to enroll the keys."
fi

sed -e "s/%IMAGE_NAME%/$IMAGE_NAME_ESCAPED/g" -e "s/%IMAGE_TAG%/$IMAGE_TAG_ESCAPED/g" -e "s/%TIP%/$TIP_ESCAPED/g" -e "s|%KEY_WARN%|$KEY_WARN|g" /usr/share/ublue-os/motd/bluefin.md | tr '~' '\n' | /usr/bin/glow -s auto -w 78 -
