#!/usr/bin/env bash
set -x

# This little workaround is used to ensure
# we use our $USER inside the containers, without
# resorting to creating devcontainer.json or similar stuff
# Ref: https://github.com/89luca89/distrobox/blob/main/docs/posts/integrate_vscode_distrobox.md#third-step-podman-wrapper
arr=("$@")
for i in "${!arr[@]}"; do
    if [[ ${arr[$i]} == *"root:root"* ]]; then
        arr[$i]="$(echo "${arr[$i]}" | sed "s|root:root|$USER:$USER|g")"
    fi
done

docker "${arr[@]}"
