name: bluefin 38
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
      - "system_files/kinoite/**"
  schedule:
    - cron: "42 16 * * *" # 16:42 UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: 38

  scan:
    uses: ./.github/workflows/reusable-image-scan.yml
    needs: build
    secrets: inherit
    with:
      images: ${{ needs.build.outputs.images }}
