name: Aurora ISO Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * sun'  # 02:00 Sunday
jobs:
  build-40:
    name: Aurora 40
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      brand_name: aurora
      fedora_version: 40
