name: GTS ISO
on:
  # schedule:
  #   - cron: '0 2 * * sun'  # 02:00 Sunday
  workflow_dispatch:
  workflow_call: 

jobs:
  build-iso-gts:
    name: Build GTS ISOs
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    strategy:
      matrix:
        brand_name: [bluefin]
    with:
      brand_name: ${{ matrix.brand_name }}
      fedora_version: gts

