name: Anaconda GTS ISO
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-iso-gts:
    name: Build GTS ISOs
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      stream_name: gts
