name: Bluefin Latest ISO Build
on:
  workflow_dispatch:

jobs:
  build-latest:
    name: Bluefin Latest
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: 40
