name: Bluefin Latest ISO
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * sun'  # 04:00 Sunday
  

jobs:
  build-latest:
    name: Bluefin Latest
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: latest
