name: Anaconda Stable ISO
on:
  workflow_dispatch:

jobs:
  build-iso-stable:
    name: Build Stable ISOs
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      stream_name: stable
