name: Bluefin 39
on:
  pull_request:
    branches:
      - main
      - testing
  schedule:
    - cron: '41 5 * * 0'  # 5:41 UTC Weekly on Sundays
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: 39
