name: Beta Images
on:
  #merge_group:
  pull_request:
    branches:
      - beta
    paths-ignore:
      - "**.md"
      - ".github/workflows/*validate*.yml"
      - "system_files/shared/etc/bazaar/**"
      - "flatpaks/**"
  push:
    branches:
      - beta
    paths-ignore:
      - "**.md"
      - ".github/workflows/*validate*.yml"
      - "system_files/shared/etc/bazaar/**"
      - "flatpaks/**"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  build-image-beta:
    name: Build Beta Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["bluefin"]
    with:
      brand_name: ${{ matrix.brand_name }}
      stream_name: beta

  generate-release:
    name: Generate Release
    needs: [build-image-beta]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["beta"]'