name: Build All Images
on:
    workflow_dispatch:

permissions:
    contents: read
    packages: write
    id-token: write

jobs:
    build-image-gts:
        uses: ./.github/workflows/build-image-gts.yml
        secrets: inherit
    build-image-stable:
        uses: ./.github/workflows/build-image-stable.yml
        secrets: inherit
    build-image-latest-main:
        uses: ./.github/workflows/build-image-latest-main.yml
        secrets: inherit
    build-image-latest-hwe:
        uses: ./.github/workflows/build-image-latest-hwe.yml
        secrets: inherit
    build-image-beta:
        uses: ./.github/workflows/build-image-beta.yml
        secrets: inherit
