name: Backport Merged Pull Requests

on:
  pull_request_target:
    types: [closed]

permissions: {}

jobs:
  cherry-pick:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'cherry-pick')

    runs-on: ubuntu-latest

    steps:
      - name: Generate a GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          client-id: ${{ secrets.BLUEFINBOT_APP_ID }}
          private-key: ${{ secrets.BLUEFINBOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Configure Git Author
        run: |
          git config --global user.name "bluefin-backport-bot[bot]"
          git config --global user.email "bluefin-backport-bot[bot]@users.noreply.github.com"

      - name: Create Backport Pull Requests
        uses: korthout/backport-action@66065406958f46e82238fd59546f5a99e69e22aa # v4.5.2
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          target_branches: "stable"
          add_labels: "backported-to-stable"
          pull_description: |
            This is an automated backport of PR #${{ github.event.pull_request.number }} to \`stable\`.

            **_Please review the changes carefully._**

            ### Original PR Description:
            ${{ github.event.pull_request.body }}
