name: Cleanup Old Images
on:
  schedule:
    - cron: "15 0 * * 0" # 0015 UTC on Sundays
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@792f00f0ff1466b4ee1eeb46049aeeb6ba7d1c8d # v1.0.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: aurora,aurora-asus,aurora-asus-nvidia,aurora-dx,aurora-dx-asus,aurora-dx-hwe,aurora-dx-asus-nvidia,aurora-dx-hwe-nvidia,aurora-dx-nvidia,aurora-dx-surface,aurora-dx-surface-nvidia,aurora-hwe,aurora-hwe-nvidia,aurora-surface,aurora-nvidia,aurora-surface,aurora-surface-nvidia,bluefin,bluefin-asus-nvidia,bluefin-dx,bluefin-dx-asus-nvidia,bluefin-dx-hwe,bluefin-dx-hwe-nvidia,bluefin-dx-nvidia,bluefin-hwe,bluefin-nvidia 
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7
