name: Cleanup Old Images
on:
  schedule:
    - cron: "15 0 * * 0" # 0015 UTC on Sundays
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: bluefin,bluefin-dx,bluefin-nvidia-open,bluefin-dx-nvidia-open
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7
