on:
  workflow_call:
    inputs:
      stream_name:
        description: "Release Tag (e.g. stable)"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      handwritten:
        description: "Small Changelog about changes in this build"
      stream_name:
        description: "Release Tag (e.g. stable)"
        required: true
        type: choice
        options:
          - '["stable"]'

permissions: {}

name: Generate Release
jobs:
  generate-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson( inputs.stream_name ) }}

    steps:
      - name: Checkout last 500 commits (for <commits> to work)
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 500

      - name: Install Just
        run: |
          /home/linuxbrew/.linuxbrew/bin/brew install just
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Check Just Syntax
        shell: bash
        run: |
          just check

      - name: Install ORAS
        uses: oras-project/setup-oras@1d808f7d7f6995cc68b7bf507bfe5c5446e1dc9d # v2.0.1

      - name: Generate Release Text
        id: generate-release-text
        shell: bash
        run: |
          just changelogs "${{ matrix.version }}" "${{ inputs.handwritten }}"
          source ./output.env
          echo "title=${TITLE}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        if: contains(fromJson('["stable"]'), matrix.version) && (github.event.schedule == '0 1 * * TUE' || contains(fromJson('["workflow_dispatch", "workflow_call"]'), github.event_name))
        with:
          name: ${{ steps.generate-release-text.outputs.title }}
          tag_name: ${{ steps.generate-release-text.outputs.tag }}
          body_path: ./changelog.md
          make_latest: ${{ matrix.version == 'stable' }}
          prerelease: false
