name: Notify Docs on Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Test release tag name (e.g., 'v1.0.0')"
        required: true
        type: string
        default: "v1.0.0-test"
      release_name:
        description: "Test release name"
        required: true
        type: string
        default: "Test Release"
      release_body:
        description: "Test release body/changelog"
        required: false
        type: string
        default: "This is a test release for workflow validation."
      prerelease:
        description: "Is this a prerelease?"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  notify-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Notify bluefin-docs repository
        uses: peter-evans/repository-dispatch@v2 
        with:
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          repository: ublue-os/bluefin-docs
          event-type: bluefin-release
          client-payload: |
            {
              "release": {
                "tag_name": "${{ github.event_name == 'workflow_dispatch' && inputs.tag_name || github.event.release.tag_name }}",
                "name": "${{ github.event_name == 'workflow_dispatch' && inputs.release_name || github.event.release.name }}",
                "body": ${{ github.event_name == 'workflow_dispatch' && toJSON(inputs.release_body) || toJSON(github.event.release.body) }},
                "html_url": "${{ github.event_name == 'workflow_dispatch' && format('https://github.com/{0}/releases/tag/{1}', github.repository, inputs.tag_name) || github.event.release.html_url }}",
                "prerelease": ${{ github.event_name == 'workflow_dispatch' && inputs.prerelease || github.event.release.prerelease }},
                "draft": ${{ github.event_name == 'workflow_dispatch' && false || github.event.release.draft }},
                "created_at": "${{ github.event_name == 'workflow_dispatch' && '' || github.event.release.created_at }}",
                "published_at": "${{ github.event_name == 'workflow_dispatch' && '' || github.event.release.published_at }}"
              },
              "repository": {
                "name": "${{ github.repository }}",
                "html_url": "${{ github.event.repository.html_url }}"
              },
              "test_mode": ${{ github.event_name == 'workflow_dispatch' }}
            }
